# Generated by Django 5.2.17 on 2026-10-07 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('robot_type', models.CharField(choices=[('simulated', 'Simulated'), ('physical', 'Physical')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='RobotBlockFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_files', to='BlockBot.robot')),
            ],
        ),
    ]
